name: CI of Build, Deploy, Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env: 
  DOTNET_VERSION: 3.0.100

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Copy Test Repo
      run: |
        openssl aes-256-cbc -K $encrypted_4ac443e3798c_key -iv $encrypted_4ac443e3798c_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d 
        chmod 600 ~/.ssh/id_rsa
        eval $(ssh-agent)
        ssh-add ~/.ssh/id_rsa
        cp .travis/ssh_config ~/.ssh/config
        git config --global user.name "cloud8little"
        git config --global user.email "413074538@qq.com"
        
    - name: Install
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
