name: CI of Build, Deploy, Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env: 
  DOTNET_VERSION: 3.1.100

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Config Git Environment
      env:
          ACTION_DEPLOY_KEY: ${{secrets.ACTION_DEPLOY_KEY}}
      run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "cloud8little"
          git config --global user.email "413074538@qq.com"
    - name: Copy Test Repo and Build docker image and Run test cases
      run: |
        dotnet --version
        git clone git@github.com:superboyiii/NEO-TEST.git ./neo-test
        cd ./neo-test/
        git checkout packtest
        cd ..
        docker build -f consensus-container/Dockerfile -t consensus .
        docker build -f ordinary-container/Dockerfile -t ordinary .
        docker network create --driver bridge --subnet=172.18.12.0/16 --gateway=172.18.1.1 neonet
        docker run -d --name cns --network=neonet --ip 172.18.12.1 consensus
        docker run --name cli_test --network=neonet --ip 172.18.12.2 ordinary ./run_test.sh

